// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddSong(ctx context.Context, arg AddSongParams) (Song, error)
	DeleteSong(ctx context.Context, id uuid.UUID) error
	GetSong(ctx context.Context, arg GetSongParams) (GetSongRow, error)
	GetSongLyrics(ctx context.Context, arg GetSongLyricsParams) ([]string, error)
	ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
}

var _ Querier = (*Queries)(nil)
